#!/usr/bin/env python
# -*- coding: utf-8 -*-
####################################################################
# 프로그램명 : hough_drive_c1.py
# 작 성 자 : (주)자이트론
# 생 성 일 : 2020년 07월 23일
# 본 프로그램은 상업 라이센스에 의해 제공되므로 무단 배포 및 상업적 이용을 금합니다.
####################################################################

import rospy
import rospkg
import time
import numpy as np
import cv2
import math
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
from xycar_msgs.msg import xycar_motor
import signal
import sys
import os

# Signal handler for graceful shutdown
def signal_handler(sig, frame):
    time.sleep(3)
    os.system('killall -9 python rosout')
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)

# Global variables
image = np.empty(shape=[0])
bridge = CvBridge()
motor = None
Width = 320
Height = 240
Offset = 160
Gap = 60
cam = False
cam_debug = True
sub_f = 0
time_c = 0

# Image callback function
def img_callback(data):
    global image, sub_f, time_c
    sub_f += 1
    if time.time() - time_c > 1:
        time_c = time.time()
        sub_f = 0
    image = bridge.imgmsg_to_cv2(data, "bgr8")

# Publish xycar_motor msg
def drive(Angle, Speed): 
    global motor
    motor_msg = xycar_motor()
    motor_msg.angle = Angle
    motor_msg.speed = Speed
    motor.publish(motor_msg)

# Draw lines on the image
def draw_lines(img, lines):
    global Offset
    for line in lines:
        x1, y1, x2, y2 = line[0]
        img = cv2.line(img, (x1, y1 + Offset), (x2, y2 + Offset), (0, 255, 0), 2)
    return img

# Draw rectangles on the image
def draw_rectangle(img, lpos, rpos, offset=0):
    center = int((lpos + rpos) / 2)
    cv2.rectangle(img, (lpos - 2, 7 + offset), (lpos + 2, 12 + offset), (0, 0, 0), 2)
    cv2.rectangle(img, (rpos - 2, 7 + offset), (rpos + 2, 12 + offset), (255, 0, 0), 2)
    cv2.rectangle(img, (center - 2, 7 + offset), (center + 2, 12 + offset), (0, 255, 0), 2)
    cv2.rectangle(img, (157, 7 + offset), (162, 12 + offset), (0, 0, 255), 2)
    return img

# Divide lines into left and right
def divide_left_right(lines):
    global Width
    low_slope_threshold = 0
    high_slope_threshold = 20
    slopes = []
    new_lines = []

    for line in lines:
        x1, y1, x2, y2 = line[0]
        slope = float('inf') if x2 - x1 == 0 else float(y2 - y1) / float(x2 - x1)
        if low_slope_threshold < abs(slope) < high_slope_threshold:
            slopes.append(slope)
            new_lines.append(line[0])

    left_lines = []
    right_lines = []
    th = -10

    for j in range(len(slopes)):
        Line = new_lines[j]
        slope = slopes[j]
        x1, y1, x2, y2 = Line

        if (slope < 0) and (x2 < Width / 2 - th):
            left_lines.append([Line.tolist()])
        elif (slope > 0) and (x1 > Width / 2 + th):
            right_lines.append([Line.tolist()])

    return left_lines, right_lines

# Get the position of the line
def get_line_pos(img, lines, left=False, right=False):
    global Width, Height, Offset, Gap, cam_debug
    x_sum = y_sum = m_sum = 0.0
    size = len(lines)
    m = b = 0

    if size != 0:
        for line in lines:
            x1, y1, x2, y2 = line[0]
            x_sum += x1 + x2
            y_sum += y1 + y2
            m_sum += float(y2 - y1) / float(x2 - x1)

        x_avg = x_sum / (size * 2)
        y_avg = y_sum / (size * 2)
        m = m_sum / size
        b = y_avg - m * x_avg

    if m == 0 and b == 0:
        pos = 0 if left else Width
    else:
        y = Gap / 2
        pos = (y - b) / m

        if cam_debug:
            b += Offset
            xs = (Height - b) / float(m)
            xe = ((Height / 2) - b) / float(m)
            cv2.line(img, (int(xs), int(Height)), (int(xe), int(Height / 2)), (255, 0, 0), 3)

    return img, int(pos)

# Stop line detection function
def stop(all_lines, flag, line_count, stop_time):
    line_len = all_lines
    print("all_lines", line_len)

    if (line_count == 1) and (line_len > 30):
        flag = 0
        line_count = 2
        return line_count, flag, stop_time

    if line_len > 30:
        flag = 1
        line_count = 1
        print("flag up")
        stop_time = time.time() + 10.5
        print("stop_time:", stop_time, " time:", time.time())

    return line_count, flag, stop_time

# Process image and return positions of left and right lines
def process_image(frame):
    global Width, Offset, Gap, cam, cam_debug, img
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    roi = gray[Offset : Offset + Gap, 0 : Width]
    blur_gray = cv2.GaussianBlur(roi, (5, 5), 3)
    edge_img = cv2.Canny(np.uint8(blur_gray), 170, 200, 5)
    all_lines = cv2.HoughLinesP(edge_img, 1, math.pi / 180, 30, 30, 2)

    if cam:
        cv2.imshow('calibration', frame)

    if all_lines is None:
        return Width / 2, Width / 2, False

    left_lines, right_lines = divide_left_right(all_lines)
    frame, lpos = get_line_pos(frame, left_lines, left=True)
    frame, rpos = get_line_pos(frame, right_lines, right=True)

    if cam_debug:
        frame = draw_lines(frame, left_lines)
        frame = draw_lines(frame, right_lines)
        frame = cv2.line(frame, (115, 117), (205, 117), (0, 255, 255), 2)
        frame = draw_rectangle(frame, lpos, rpos, offset=Offset)
        frame = cv2.rectangle(frame, (0, Offset), (int(Width), Offset + Gap), (255, 202, 204), 2)

    img = frame
    return lpos, rpos, len(all_lines), True

# Draw steering angle on the image
def draw_steer(steer_angle):
    global Width, Height, img
    arrow = cv2.imread('/home/pi/xycar_ws/src/base/src/steer_arrow.png')
    origin_Height = arrow.shape[0]
    origin_Width = arrow.shape[1]
    steer_wheel_center = origin_Height * 0.74
    arrow_Height = Height / 2
    arrow_Width = (arrow_Height * 462) / 728
    arrow_Height = int(arrow_Height)
    arrow_Width = int(arrow_Width)
    matrix = cv2.getRotationMatrix2D((origin_Width / 2, steer_wheel_center), (-steer_angle) * 1.5, 0.7)
    arrow = cv2.warpAffine(arrow, matrix, (origin_Width + 60, origin_Height))
    arrow = cv2.resize(arrow, dsize=(arrow_Width, arrow_Height), interpolation=cv2.INTER_AREA)
    gray_arrow = cv2.cvtColor(arrow, cv2.COLOR_BGR2GRAY)
    _, mask = cv2.threshold(gray_arrow, 1, 255, cv2.THRESH_BINARY_INV)
    arrow_roi = img[arrow_Height: int(Height), int(Width / 2 - arrow_Width / 2) : int(Width / 2 + arrow_Width / 2)]
    arrow_roi = cv2.add(arrow, arrow_roi, mask=mask)
    res = cv2.add(arrow_roi, arrow)
    img[int(Height - arrow_Height): int(Height), int(Width / 2 - arrow_Width / 2): int(Width / 2 + arrow_Width / 2)] = res
    cv2.imshow('steer', img)

# PID controller for angle
def pid_angle(ITerm, error, b_angle, b_error, Cnt):
    Kp = 0.92
    Ki = 0.00065
    Kd = 0.0925
    dt = 1
    PTerm = Kp * error
    ITerm += Ki * error * dt
    DTerm = Kd * (error - b_error) / dt
    angle = PTerm + DTerm
    return angle, ITerm

# Main function
def start():
    global motor, image, Width, Height
    cam_record = False
    rospy.init_node('auto_drive')
    motor = rospy.Publisher('xycar_motor', xycar_motor, queue_size=1)
    rospy.Subscriber("/usb_cam/image_raw/", Image, img_callback)
    print("---------- Xycar C1 HD v1.0 ----------")
    time.sleep(3)
    t_check = time.time()
    f_n = p_angle = flag = line_count = b_angle = b_error = ITerm = Cnt = 0
    avoid_time = time.time() + 3.8
    turn_right = time.time()
    stop_time = time.time() + 10.5

    if cam_record:
        fourcc = cv2.VideoWriter_fourcc(*'DIVX')
        path = '/home/pi/xycar_ws/src/base/cam_record'
        out = cv2.VideoWriter(os.path.join(path, 'test.avi'), fourcc, 25.0, (Width, Height))

    while not rospy.is_shutdown():
        while not image.size == (Width * Height * 3):
            continue

        f_n += 1
        if (time.time() - t_check) > 1:
            t_check = time.time()
            f_n = 0
        if cam_record:
            out.write(image)

        draw_img = image.copy()
        try:
            lpos, rpos, len_all_lines, go = process_image(draw_img)
        except:
            lpos, rpos, go = process_image(draw_img)

        if time.time() > stop_time:
            line_count, flag, stop_time = stop(len_all_lines, flag, line_count, stop_time)
        if line_count == 2:
            drive(0, 0)
            cv2.waitKey(0)
            line_count = 0

        diff = rpos - lpos
        if 135 < diff < 142:
            print("straight")
        else:
            print("curve")

        if lpos == 0:
            print("lpos error")
            lpos = rpos - 130
        if rpos > lpos + 145:
            print("rpos error")
            rpos = lpos + 130

        center = (lpos + rpos) / 2
        error = (center - Width / 2)
        angle, ITerm = pid_angle(ITerm, error, b_angle, b_error, Cnt)
        steer_angle = angle * 0.4
        draw_steer(steer_angle)
        drive(angle, 22)
        cv2.waitKey(1)
        b_angle = angle
        b_error = error

if __name__ == '__main__':
    start()
